# Generated by Django 5.0.3 on 2024-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zroLocation', models.CharField(max_length=122)),
                ('ApplyFor', models.CharField(max_length=122)),
                ('connectionType', models.CharField(max_length=122)),
                ('firstName', models.CharField(max_length=122)),
                ('middleName', models.CharField(max_length=122)),
                ('lastName', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('Mobile', models.CharField(max_length=122)),
                ('Addr', models.CharField(max_length=122)),
                ('Land', models.CharField(max_length=122)),
                ('pinAdd', models.CharField(max_length=122)),
                ('locaAdd', models.CharField(max_length=122)),
                ('subLoc', models.CharField(max_length=122)),
                ('assem', models.CharField(max_length=122)),
                ('vilAdd', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
